In [1]:
import numpy as np

In [2]:
np1=np.array([1,2,3,4])

In [3]:
np1

array([1, 2, 3, 4])

In [4]:
type(np1)

numpy.ndarray

In [6]:
mat1 = np.array([[1,2],[3,4]])

In [7]:
mat1

array([[1, 2],
       [3, 4]])

In [8]:
np1.shape

(4,)

In [10]:
mat1.shape

(2, 2)

In [11]:
mat1.dtype

dtype('int32')

In [12]:
mat1[0,0] = 5

In [13]:
mat1

array([[5, 2],
       [3, 4]])

In [15]:
mat1[0,0] = "Stringdata"

ValueError: invalid literal for int() with base 10: 'Stringdata'

In [17]:
mat2 = np.arange(0,10,1)

In [18]:
mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
mat3 = np.linspace(0,10,20)

In [20]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
mat3.shape

(20,)

In [22]:
Mat4 = np.random.rand(5,5)

In [23]:
Mat4

array([[0.62916621, 0.68716231, 0.85955375, 0.67852143, 0.1236283 ],
       [0.77329824, 0.08872674, 0.44674831, 0.82656526, 0.45716488],
       [0.88919888, 0.36533808, 0.18613547, 0.60536358, 0.26735809],
       [0.16210452, 0.25893348, 0.89541256, 0.25142841, 0.00556932],
       [0.06165075, 0.80177861, 0.29944793, 0.64858701, 0.70527512]])

In [25]:
Mat4

array([[0.62916621, 0.68716231, 0.85955375, 0.67852143, 0.1236283 ],
       [0.77329824, 0.08872674, 0.44674831, 0.82656526, 0.45716488],
       [0.88919888, 0.36533808, 0.18613547, 0.60536358, 0.26735809],
       [0.16210452, 0.25893348, 0.89541256, 0.25142841, 0.00556932],
       [0.06165075, 0.80177861, 0.29944793, 0.64858701, 0.70527512]])

In [26]:
np.diag

<function numpy.diag(v, k=0)>

In [27]:
np.diag

<function numpy.diag(v, k=0)>

In [28]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [29]:
Mat4[0,0]

0.6291662056100789

In [30]:
Mat[0.1]

NameError: name 'Mat' is not defined